// THIS FILE IS AUTOGENERATED BY parse_readmes.py - do not edit by hand
// Run the script in backend/springboot/lcpy to regenerate.

export type Example = { input: string; output: string };
export type Problem = {
  id: string;
  title: string;
  difficulty: string | null;
  topics: string[];
  tags: string[];
  examples: Example[];
};

export const problems: Problem[] = [
  {
    "id": "accounts_merge",
    "title": "Accounts Merge",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Hash Table",
      "String",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Sorting"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "accounts = [[\"John\",\"johnsmith@mail.com\",\"john_newyork@mail.com\"],[\"John\",\"johnsmith@mail.com\",\"john00@mail.com\"],[\"Mary\",\"mary@mail.com\"],[\"John\",\"johnnybravo@mail.com\"]]",
        "output": "[[\"John\",\"john00@mail.com\",\"john_newyork@mail.com\",\"johnsmith@mail.com\"],[\"Mary\",\"mary@mail.com\"],[\"John\",\"johnnybravo@mail.com\"]]"
      },
      {
        "input": "accounts = [[\"Gabe\",\"Gabe0@m.co\",\"Gabe3@m.co\",\"Gabe1@m.co\"],[\"Kevin\",\"Kevin3@m.co\",\"Kevin5@m.co\",\"Kevin0@m.co\"],[\"Ethan\",\"Ethan5@m.co\",\"Ethan4@m.co\",\"Ethan0@m.co\"],[\"Hanzo\",\"Hanzo3@m.co\",\"Hanzo1@m.co\",\"Hanzo0@m.co\"],[\"Fern\",\"Fern5@m.co\",\"Fern1@m.co\",\"Fern0@m.co\"]]",
        "output": "[[\"Ethan\",\"Ethan0@m.co\",\"Ethan4@m.co\",\"Ethan5@m.co\"],[\"Gabe\",\"Gabe0@m.co\",\"Gabe1@m.co\",\"Gabe3@m.co\"],[\"Hanzo\",\"Hanzo0@m.co\",\"Hanzo1@m.co\",\"Hanzo3@m.co\"],[\"Kevin\",\"Kevin0@m.co\",\"Kevin3@m.co\",\"Kevin5@m.co\"],[\"Fern\",\"Fern0@m.co\",\"Fern1@m.co\",\"Fern5@m.co\"]]"
      }
    ]
  },
  {
    "id": "add_binary",
    "title": "Add Binary",
    "difficulty": "Easy",
    "topics": [
      "Math",
      "String",
      "Bit Manipulation",
      "Simulation"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "a = \"11\", b = \"1\"",
        "output": "\"100\""
      },
      {
        "input": "a = \"1010\", b = \"1011\"",
        "output": "\"10101\""
      }
    ]
  },
  {
    "id": "add_two_numbers",
    "title": "Add Two Numbers",
    "difficulty": "Medium",
    "topics": [
      "Linked List",
      "Math",
      "Recursion"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "l1 = [2,4,3], l2 = [5,6,4]",
        "output": "[7,0,8]"
      },
      {
        "input": "l1 = [0], l2 = [0]",
        "output": "[0]"
      }
    ]
  },
  {
    "id": "alien_dictionary",
    "title": "Alien Dictionary",
    "difficulty": "Hard",
    "topics": [
      "Array",
      "String",
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort"
    ],
    "tags": [
      "neetcode-150",
      "grind-75",
      "grind",
      "blind-75"
    ],
    "examples": [
      {
        "input": "words = [\"wrt\",\"wrf\",\"er\",\"ett\",\"rftt\"]",
        "output": "\"wertf\""
      },
      {
        "input": "words = [\"z\",\"x\"]",
        "output": "\"zx\""
      }
    ]
  },
  {
    "id": "balanced_binary_tree",
    "title": "Balanced Binary Tree",
    "difficulty": "Easy",
    "topics": [
      "Tree",
      "Depth-First Search",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "root = [3,9,20,null,null,15,7]",
        "output": "true"
      },
      {
        "input": "root = [1,2,2,3,3,null,null,4,4]",
        "output": "false"
      }
    ]
  },
  {
    "id": "basic_calculator",
    "title": "Basic Calculator",
    "difficulty": "Hard",
    "topics": [
      "Math",
      "String",
      "Stack",
      "Recursion"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "s = \"1 + 1\"",
        "output": "2"
      },
      {
        "input": "s = \" 2-1 + 2 \"",
        "output": "3"
      }
    ]
  },
  {
    "id": "best_time_to_buy_and_sell_stock",
    "title": "Best Time to Buy and Sell Stock",
    "difficulty": "Easy",
    "topics": [
      "Array",
      "Dynamic Programming"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "prices = [7,1,5,3,6,4]",
        "output": "5"
      },
      {
        "input": "prices = [7,6,4,3,1]",
        "output": "0"
      }
    ]
  },
  {
    "id": "binary_search",
    "title": "Binary Search",
    "difficulty": "Easy",
    "topics": [
      "Array",
      "Binary Search"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "nums = [-1,0,3,5,9,12], target = 9",
        "output": "4"
      },
      {
        "input": "nums = [-1,0,3,5,9,12], target = 2",
        "output": "-1"
      }
    ]
  },
  {
    "id": "binary_tree_level_order_traversal",
    "title": "Binary Tree Level Order Traversal",
    "difficulty": "Medium",
    "topics": [
      "Tree",
      "Breadth-First Search",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "root = [3,9,20,null,null,15,7]",
        "output": "[[3],[9,20],[15,7]]"
      },
      {
        "input": "root = [1]",
        "output": "[[1]]"
      }
    ]
  },
  {
    "id": "binary_tree_maximum_path_sum",
    "title": "Binary Tree Maximum Path Sum",
    "difficulty": "Hard",
    "topics": [
      "Dynamic Programming",
      "Tree",
      "Depth-First Search",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "blind-75"
    ],
    "examples": [
      {
        "input": "root = [1,2,3]",
        "output": "6"
      },
      {
        "input": "root = [-10,9,20,null,null,15,7]",
        "output": "42"
      }
    ]
  },
  {
    "id": "binary_tree_right_side_view",
    "title": "Binary Tree Right Side View",
    "difficulty": "Medium",
    "topics": [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "root = [1,2,3,null,5,null,4]",
        "output": "[1,3,4]"
      },
      {
        "input": "root = [1,2,3,4,null,null,null,5]",
        "output": "[1,3,4,5]"
      }
    ]
  },
  {
    "id": "climbing_stairs",
    "title": "Climbing Stairs",
    "difficulty": "Easy",
    "topics": [
      "Math",
      "Dynamic Programming",
      "Memoization"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "n = 2",
        "output": "2"
      },
      {
        "input": "n = 3",
        "output": "3"
      }
    ]
  },
  {
    "id": "clone_graph",
    "title": "Clone Graph",
    "difficulty": "Medium",
    "topics": [
      "Hash Table",
      "Depth-First Search",
      "Breadth-First Search",
      "Graph"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "adjList = [[2,4],[1,3],[2,4],[1,3]]",
        "output": "[[2,4],[1,3],[2,4],[1,3]]"
      },
      {
        "input": "adjList = [[]]",
        "output": "[[]]"
      }
    ]
  },
  {
    "id": "coin_change",
    "title": "Coin Change",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Dynamic Programming",
      "Breadth-First Search"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "coins = [1,2,5], amount = 11",
        "output": "3"
      },
      {
        "input": "coins = [2], amount = 3",
        "output": "-1"
      }
    ]
  },
  {
    "id": "combination_sum",
    "title": "Combination Sum",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Backtracking"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "candidates = [2,3,6,7], target = 7",
        "output": "[[2,2,3],[7]]"
      },
      {
        "input": "candidates = [2,3,5], target = 8",
        "output": "[[2,2,2,2],[2,3,3],[3,5]]"
      }
    ]
  },
  {
    "id": "construct_binary_tree_from_preorder_and_inorder_traversal",
    "title": "Construct Binary Tree from Preorder and Inorder Traversal",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Hash Table",
      "Divide and Conquer",
      "Tree",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]",
        "output": "[3,9,20,null,null,15,7]"
      },
      {
        "input": "preorder = [-1], inorder = [-1]",
        "output": "[-1]"
      }
    ]
  },
  {
    "id": "container_with_most_water",
    "title": "Container With Most Water",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Two Pointers",
      "Greedy"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "height = [1,8,6,2,5,4,8,3,7]",
        "output": "49"
      },
      {
        "input": "height = [1,1]",
        "output": "1"
      }
    ]
  },
  {
    "id": "contains_duplicate",
    "title": "Contains Duplicate",
    "difficulty": "Easy",
    "topics": [
      "Array",
      "Hash Table",
      "Sorting"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "nums = [1,2,3,1]",
        "output": "true"
      },
      {
        "input": "nums = [1,2,3,4]",
        "output": "false"
      }
    ]
  },
  {
    "id": "contiguous_array",
    "title": "Contiguous Array",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Hash Table",
      "Prefix Sum"
    ],
    "tags": [
      "grind"
    ],
    "examples": [
      {
        "input": "nums = [0,1]",
        "output": "2"
      },
      {
        "input": "nums = [0,1,0]",
        "output": "2"
      }
    ]
  },
  {
    "id": "counting_bits",
    "title": "Counting Bits",
    "difficulty": "Easy",
    "topics": [
      "Dynamic Programming",
      "Bit Manipulation"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "blind-75"
    ],
    "examples": [
      {
        "input": "n = 2",
        "output": "[0,1,1]"
      },
      {
        "input": "n = 5",
        "output": "[0,1,1,2,1,2]"
      }
    ]
  },
  {
    "id": "course_schedule",
    "title": "Course Schedule",
    "difficulty": "Medium",
    "topics": [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "numCourses = 2, prerequisites = [[1,0]]",
        "output": "true"
      },
      {
        "input": "numCourses = 2, prerequisites = [[1,0],[0,1]]",
        "output": "false"
      }
    ]
  },
  {
    "id": "course_schedule_ii",
    "title": "Course Schedule II",
    "difficulty": "Medium",
    "topics": [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind"
    ],
    "examples": [
      {
        "input": "numCourses = 2, prerequisites = [[1,0]]",
        "output": "[0,1]"
      },
      {
        "input": "numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]",
        "output": "[0,2,1,3]"
      }
    ]
  },
  {
    "id": "daily_temperatures",
    "title": "Daily Temperatures",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Stack",
      "Monotonic Stack"
    ],
    "tags": [
      "neetcode-150",
      "grind"
    ],
    "examples": [
      {
        "input": "temperatures = [73,74,75,71,69,72,76,73]",
        "output": "[1,1,4,2,1,1,0,0]"
      },
      {
        "input": "temperatures = [30,40,50,60]",
        "output": "[1,1,1,0]"
      }
    ]
  },
  {
    "id": "decode_string",
    "title": "Decode String",
    "difficulty": "Medium",
    "topics": [
      "String",
      "Stack",
      "Recursion"
    ],
    "tags": [
      "grind"
    ],
    "examples": [
      {
        "input": "s = \"3[a]2[bc]\"",
        "output": "\"aaabcbc\""
      },
      {
        "input": "s = \"3[a2[c]]\"",
        "output": "\"accaccacc\""
      }
    ]
  },
  {
    "id": "decode_ways",
    "title": "Decode Ways",
    "difficulty": "Medium",
    "topics": [
      "String",
      "Dynamic Programming"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "s = \"12\"",
        "output": "2"
      },
      {
        "input": "s = \"226\"",
        "output": "3"
      }
    ]
  },
  {
    "id": "design_add_and_search_words_data_structure",
    "title": "Design Add and Search Words Data Structure",
    "difficulty": "Medium",
    "topics": [
      "String",
      "Depth-First Search",
      "Design",
      "Trie"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75"
    ],
    "examples": []
  },
  {
    "id": "design_in_memory_file_system",
    "title": "Design In-Memory File System",
    "difficulty": "Hard",
    "topics": [
      "Design",
      "Trie",
      "Hash Table",
      "String"
    ],
    "tags": [
      "grind"
    ],
    "examples": [
      {
        "input": "",
        "output": ""
      }
    ]
  },
  {
    "id": "diagonal_traverse",
    "title": "Diagonal Traverse",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Matrix",
      "Simulation"
    ],
    "tags": [
      "**LeetCode:**",
      "[Problem",
      "498](https://leetcode.com/problems/diagonal-traverse/description/)"
    ],
    "examples": [
      {
        "input": "mat = [[1,2,3],[4,5,6],[7,8,9]]",
        "output": "[1,2,4,7,5,3,6,8,9]"
      },
      {
        "input": "mat = [[1,2],[3,4]]",
        "output": "[1,2,3,4]"
      }
    ]
  },
  {
    "id": "diameter_of_binary_tree",
    "title": "Diameter of Binary Tree",
    "difficulty": "Easy",
    "topics": [
      "Tree",
      "Depth-First Search",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "root = [1,2,3,4,5]",
        "output": "3"
      },
      {
        "input": "root = [1,2]",
        "output": "1"
      }
    ]
  },
  {
    "id": "encode_and_decode_strings",
    "title": "Encode and Decode Strings",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "String",
      "Design"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "dummy_input = [\"Hello\",\"World\"]",
        "output": "\"Hello,World\""
      }
    ]
  },
  {
    "id": "evaluate_reverse_polish_notation",
    "title": "Evaluate Reverse Polish Notation",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Math",
      "Stack"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "tokens = [\"2\",\"1\",\"+\",\"3\",\"*\"]",
        "output": "9"
      },
      {
        "input": "tokens = [\"4\",\"13\",\"5\",\"/\",\"+\"]",
        "output": "6"
      }
    ]
  },
  {
    "id": "find_all_anagrams_in_a_string",
    "title": "Find All Anagrams in a String",
    "difficulty": "Medium",
    "topics": [
      "Hash Table",
      "String",
      "Sliding Window"
    ],
    "tags": [
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "s = \"cbaebabacd\", p = \"abc\"",
        "output": "[0,6]"
      },
      {
        "input": "s = \"abab\", p = \"ab\"",
        "output": "[0,1,2]"
      }
    ]
  },
  {
    "id": "find_k_closest_elements",
    "title": "Find K Closest Elements",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Two Pointers",
      "Binary Search",
      "Sliding Window",
      "Sorting",
      "Heap (Priority Queue)"
    ],
    "tags": [
      "grind"
    ],
    "examples": [
      {
        "input": "arr = [1,2,3,4,5], k = 4, x = 3",
        "output": "[1,2,3,4]"
      },
      {
        "input": "arr = [1,1,2,3,4,5], k = 4, x = -1",
        "output": "[1,1,2,3]"
      }
    ]
  },
  {
    "id": "find_median_from_data_stream",
    "title": "Find Median from Data Stream",
    "difficulty": "Hard",
    "topics": [
      "Two Pointers",
      "Design",
      "Sorting",
      "Heap (Priority Queue)",
      "Data Stream"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": []
  },
  {
    "id": "find_minimum_in_rotated_sorted_array",
    "title": "Find Minimum in Rotated Sorted Array",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Binary Search"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "nums = [3,4,5,1,2]",
        "output": "1"
      },
      {
        "input": "nums = [4,5,6,7,0,1,2]",
        "output": "0"
      }
    ]
  },
  {
    "id": "find_the_duplicate_number",
    "title": "Find the Duplicate Number",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Two Pointers",
      "Binary Search",
      "Bit Manipulation"
    ],
    "tags": [
      "neetcode-150",
      "grind"
    ],
    "examples": [
      {
        "input": "nums = [1,3,4,2,2]",
        "output": "2"
      },
      {
        "input": "nums = [3,1,3,4,2]",
        "output": "3"
      }
    ]
  },
  {
    "id": "first_bad_version",
    "title": "First Bad Version",
    "difficulty": "Easy",
    "topics": [
      "Binary Search",
      "Interactive"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "n = 5, bad = 4",
        "output": "4"
      },
      {
        "input": "n = 1, bad = 1",
        "output": "1"
      }
    ]
  },
  {
    "id": "flood_fill",
    "title": "Flood Fill",
    "difficulty": "Easy",
    "topics": [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Matrix"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "image = [[1,1,1],[1,1,0],[1,0,1]], sr = 1, sc = 1, color = 2",
        "output": "[[2,2,2],[2,2,0],[2,0,1]]"
      },
      {
        "input": "image = [[0,0,0],[0,0,0]], sr = 0, sc = 0, color = 0",
        "output": "[[0,0,0],[0,0,0]]"
      }
    ]
  },
  {
    "id": "gas_station",
    "title": "Gas Station",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Greedy"
    ],
    "tags": [
      "neetcode-150",
      "grind"
    ],
    "examples": [
      {
        "input": "gas = [1,2,3,4,5], cost = [3,4,5,1,2]",
        "output": "3"
      },
      {
        "input": "gas = [2,3,4], cost = [3,4,3]",
        "output": "-1"
      }
    ]
  },
  {
    "id": "graph_valid_tree",
    "title": "Graph Valid Tree",
    "difficulty": "Medium",
    "topics": [
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Graph"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "n = 5, and edges = [[0,1], [0,2], [0,3], [1,4]]",
        "output": "true"
      },
      {
        "input": "n = 5, and edges = [[0,1], [1,2], [2,3], [1,3], [1,4]]",
        "output": "false"
      }
    ]
  },
  {
    "id": "group_anagrams",
    "title": "Group Anagrams",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Hash Table",
      "String",
      "Sorting"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "blind-75"
    ],
    "examples": [
      {
        "input": "strs = [\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]",
        "output": "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]"
      },
      {
        "input": "strs = [\"\"]",
        "output": "[[\"\"]]"
      }
    ]
  },
  {
    "id": "house_robber",
    "title": "House Robber",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Dynamic Programming"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75"
    ],
    "examples": [
      {
        "input": "nums = [1,2,3,1]",
        "output": "4"
      },
      {
        "input": "nums = [2,7,9,3,1]",
        "output": "12"
      }
    ]
  },
  {
    "id": "house_robber_ii",
    "title": "House Robber II",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Dynamic Programming"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "blind-75"
    ],
    "examples": [
      {
        "input": "nums = [2,3,2]",
        "output": "3"
      },
      {
        "input": "nums = [1,2,3,1]",
        "output": "4"
      }
    ]
  },
  {
    "id": "implement_queue_using_stacks",
    "title": "Implement Queue using Stacks",
    "difficulty": "Easy",
    "topics": [
      "Stack",
      "Design",
      "Queue"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": []
  },
  {
    "id": "implement_trie_prefix_tree",
    "title": "Implement Trie (Prefix Tree)",
    "difficulty": "Medium",
    "topics": [
      "Hash Table",
      "String",
      "Design",
      "Trie"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": []
  },
  {
    "id": "insert_interval",
    "title": "Insert Interval",
    "difficulty": "Medium",
    "topics": [
      "Array"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "intervals = [[1,3],[6,9]], newInterval = [2,5]",
        "output": "[[1,5],[6,9]]"
      },
      {
        "input": "intervals = [[1,2],[3,5],[6,7],[8,10],[12,16]], newInterval = [4,8]",
        "output": "[[1,2],[3,10],[12,16]]"
      }
    ]
  },
  {
    "id": "invert_binary_tree",
    "title": "Invert Binary Tree",
    "difficulty": "Easy",
    "topics": [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "root = [4,2,7,1,3,6,9]",
        "output": "[4,7,2,9,6,3,1]"
      },
      {
        "input": "root = [2,1,3]",
        "output": "[2,3,1]"
      }
    ]
  },
  {
    "id": "jump_game",
    "title": "Jump Game",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Dynamic Programming",
      "Greedy"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "nums = [2,3,1,1,4]",
        "output": "true"
      },
      {
        "input": "nums = [3,2,1,0,4]",
        "output": "false"
      }
    ]
  },
  {
    "id": "k_closest_points_to_origin",
    "title": "K Closest Points to Origin",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Math",
      "Divide and Conquer",
      "Geometry",
      "Sorting",
      "Heap (Priority Queue)",
      "Quickselect"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "points = [[1,3],[-2,2]], k = 1",
        "output": "[[-2,2]]"
      },
      {
        "input": "points = [[3,3],[5,-1],[-2,4]], k = 2",
        "output": "[[3,3],[-2,4]]"
      }
    ]
  },
  {
    "id": "kth_smallest_element_in_a_bst",
    "title": "Kth Smallest Element in a BST",
    "difficulty": "Medium",
    "topics": [
      "Tree",
      "Depth-First Search",
      "Binary Search Tree",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "root = [3,1,4,null,2], k = 1",
        "output": "1"
      },
      {
        "input": "root = [5,3,6,2,4,null,null,1], k = 3",
        "output": "3"
      }
    ]
  },
  {
    "id": "largest_rectangle_in_histogram",
    "title": "Largest Rectangle in Histogram",
    "difficulty": "Hard",
    "topics": [
      "Array",
      "Stack",
      "Monotonic Stack"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "heights = [2,1,5,6,2,3]",
        "output": "10"
      },
      {
        "input": "heights = [2,4]",
        "output": "4"
      }
    ]
  },
  {
    "id": "letter_combinations_of_a_phone_number",
    "title": "Letter Combinations of a Phone Number",
    "difficulty": "Medium",
    "topics": [
      "Hash Table",
      "String",
      "Backtracking"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "digits = \"23\"",
        "output": "[\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]"
      },
      {
        "input": "digits = \"\"",
        "output": "[]"
      }
    ]
  },
  {
    "id": "linked_list_cycle",
    "title": "Linked List Cycle",
    "difficulty": "Easy",
    "topics": [
      "Hash Table",
      "Linked List",
      "Two Pointers"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "head = [3,2,0,-4], pos = 1",
        "output": "true"
      },
      {
        "input": "head = [1,2], pos = 0",
        "output": "true"
      }
    ]
  },
  {
    "id": "longest_common_subsequence",
    "title": "Longest Common Subsequence",
    "difficulty": "Medium",
    "topics": [
      "String",
      "Dynamic Programming"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "blind-75"
    ],
    "examples": [
      {
        "input": "text1 = \"abcde\", text2 = \"ace\"",
        "output": "3"
      },
      {
        "input": "text1 = \"abc\", text2 = \"abc\"",
        "output": "3"
      }
    ]
  },
  {
    "id": "longest_consecutive_sequence",
    "title": "Longest Consecutive Sequence",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Hash Table",
      "Union Find"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "blind-75"
    ],
    "examples": [
      {
        "input": "nums = [100,4,200,1,3,2]",
        "output": "4"
      },
      {
        "input": "nums = [0,3,7,2,5,8,4,6,0,1]",
        "output": "9"
      }
    ]
  },
  {
    "id": "longest_increasing_subsequence",
    "title": "Longest Increasing Subsequence",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Binary Search",
      "Dynamic Programming"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "blind-75"
    ],
    "examples": [
      {
        "input": "nums = [10,9,2,5,3,7,101,18]",
        "output": "4"
      },
      {
        "input": "nums = [0,1,0,3,2,3]",
        "output": "4"
      }
    ]
  },
  {
    "id": "longest_palindrome",
    "title": "Longest Palindrome",
    "difficulty": "Easy",
    "topics": [
      "Hash Table",
      "String",
      "Greedy"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "s = \"abccccdd\"",
        "output": "7"
      },
      {
        "input": "s = \"a\"",
        "output": "1"
      }
    ]
  },
  {
    "id": "longest_palindromic_substring",
    "title": "Longest Palindromic Substring",
    "difficulty": "Medium",
    "topics": [
      "Two Pointers",
      "String",
      "Dynamic Programming"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "s = \"babad\"",
        "output": "\"bab\""
      },
      {
        "input": "s = \"cbbd\"",
        "output": "\"bb\""
      }
    ]
  },
  {
    "id": "longest_repeating_character_replacement",
    "title": "Longest Repeating Character Replacement",
    "difficulty": "Medium",
    "topics": [
      "Hash Table",
      "String",
      "Sliding Window"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "s = \"ABAB\", k = 2",
        "output": "4"
      },
      {
        "input": "s = \"AABABBA\", k = 1",
        "output": "4"
      }
    ]
  },
  {
    "id": "longest_substring_without_repeating_characters",
    "title": "Longest Substring Without Repeating Characters",
    "difficulty": "Medium",
    "topics": [
      "Hash Table",
      "String",
      "Sliding Window"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "s = \"abcabcbb\"",
        "output": "3"
      },
      {
        "input": "s = \"bbbbb\"",
        "output": "1"
      }
    ]
  },
  {
    "id": "lowest_common_ancestor_of_a_binary_search_tree",
    "title": "Lowest Common Ancestor of a Binary Search Tree",
    "difficulty": "Medium",
    "topics": [
      "Tree",
      "Depth-First Search",
      "Binary Search Tree",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8",
        "output": "6"
      },
      {
        "input": "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 4",
        "output": "2"
      }
    ]
  },
  {
    "id": "lowest_common_ancestor_of_a_binary_tree",
    "title": "Lowest Common Ancestor of a Binary Tree",
    "difficulty": "Medium",
    "topics": [
      "Tree",
      "Depth-First Search",
      "Binary Tree"
    ],
    "tags": [
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1",
        "output": "3"
      },
      {
        "input": "root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 4",
        "output": "5"
      }
    ]
  },
  {
    "id": "lru_cache",
    "title": "LRU Cache",
    "difficulty": "Medium",
    "topics": [
      "Hash Table",
      "Linked List",
      "Design",
      "Doubly-Linked List"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": []
  },
  {
    "id": "majority_element",
    "title": "Majority Element",
    "difficulty": "Easy",
    "topics": [
      "Array",
      "Hash Table",
      "Divide and Conquer",
      "Sorting",
      "Counting"
    ],
    "tags": [
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "nums = [3,2,3]",
        "output": "3"
      },
      {
        "input": "nums = [2,2,1,1,1,2,2]",
        "output": "2"
      }
    ]
  },
  {
    "id": "maximum_depth_of_binary_tree",
    "title": "Maximum Depth of Binary Tree",
    "difficulty": "Easy",
    "topics": [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "root = [3,9,20,null,null,15,7]",
        "output": "3"
      },
      {
        "input": "root = [1,null,2]",
        "output": "2"
      }
    ]
  },
  {
    "id": "maximum_product_subarray",
    "title": "Maximum Product Subarray",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Dynamic Programming"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75"
    ],
    "examples": [
      {
        "input": "nums = [2,3,-2,4]",
        "output": "6"
      },
      {
        "input": "nums = [-2,0,-1]",
        "output": "0"
      }
    ]
  },
  {
    "id": "maximum_profit_in_job_scheduling",
    "title": "Maximum Profit in Job Scheduling",
    "difficulty": "Hard",
    "topics": [
      "Array",
      "Binary Search",
      "Dynamic Programming",
      "Sorting"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "startTime = [1,2,3,3], endTime = [3,4,5,6], profit = [50,10,40,70]",
        "output": "120"
      },
      {
        "input": "startTime = [1,2,3,4,6], endTime = [3,5,10,6,9], profit = [20,20,100,70,60]",
        "output": "150"
      }
    ]
  },
  {
    "id": "maximum_subarray",
    "title": "Maximum Subarray",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Divide and Conquer",
      "Dynamic Programming"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "nums = [-2,1,-3,4,-1,2,1,-5,4]",
        "output": "6"
      },
      {
        "input": "nums = [1]",
        "output": "1"
      }
    ]
  },
  {
    "id": "maximum_width_of_binary_tree",
    "title": "Maximum Width of Binary Tree",
    "difficulty": "Medium",
    "topics": [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree"
    ],
    "tags": [
      "grind"
    ],
    "examples": [
      {
        "input": "root = [1,3,2,5,3,null,9]",
        "output": "4"
      },
      {
        "input": "root = [1,3,2,5,null,null,9,6,null,7]",
        "output": "7"
      }
    ]
  },
  {
    "id": "median_of_two_sorted_arrays",
    "title": "Median of Two Sorted Arrays",
    "difficulty": "Hard",
    "topics": [
      "Array",
      "Binary Search",
      "Divide and Conquer"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "nums1 = [1,3], nums2 = [2]",
        "output": "2.00000"
      },
      {
        "input": "nums1 = [1,2], nums2 = [3,4]",
        "output": "2.50000"
      }
    ]
  },
  {
    "id": "meeting_rooms",
    "title": "Meeting Rooms",
    "difficulty": "Easy",
    "topics": [
      "Array",
      "Sorting"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "[[0,30],[5,10],[15,20]]",
        "output": "false"
      },
      {
        "input": "[[7,10],[2,4]]",
        "output": "true"
      }
    ]
  },
  {
    "id": "meeting_rooms_ii",
    "title": "Meeting Rooms II",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Two Pointers",
      "Greedy",
      "Sorting",
      "Heap (Priority Queue)"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "[[0,30],[5,10],[15,20]]",
        "output": "2"
      },
      {
        "input": "[[7,10],[2,4]]",
        "output": "1"
      }
    ]
  },
  {
    "id": "merge_intervals",
    "title": "Merge Intervals",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Sorting"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "intervals = [[1,3],[2,6],[8,10],[15,18]]",
        "output": "[[1,6],[8,10],[15,18]]"
      },
      {
        "input": "intervals = [[1,4],[4,5]]",
        "output": "[[1,5]]"
      }
    ]
  },
  {
    "id": "merge_k_sorted_lists",
    "title": "Merge k Sorted Lists",
    "difficulty": "Hard",
    "topics": [
      "Linked List",
      "Divide and Conquer",
      "Heap (Priority Queue)",
      "Merge Sort"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "lists = [[1,4,5],[1,3,4],[2,6]]",
        "output": "[1,1,2,3,4,4,5,6]"
      },
      {
        "input": "lists = []",
        "output": "[]"
      }
    ]
  },
  {
    "id": "merge_two_sorted_lists",
    "title": "Merge Two Sorted Lists",
    "difficulty": "Easy",
    "topics": [
      "Linked List",
      "Recursion"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "list1 = [1,2,4], list2 = [1,3,4]",
        "output": "[1,1,2,3,4,4]"
      },
      {
        "input": "list1 = [], list2 = []",
        "output": "[]"
      }
    ]
  },
  {
    "id": "middle_of_the_linked_list",
    "title": "Middle of the Linked List",
    "difficulty": "Easy",
    "topics": [
      "Linked List",
      "Two Pointers"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "head = [1,2,3,4,5]",
        "output": "[3,4,5]"
      },
      {
        "input": "head = [1,2,3,4,5,6]",
        "output": "[4,5,6]"
      }
    ]
  },
  {
    "id": "min_stack",
    "title": "Min Stack",
    "difficulty": "Medium",
    "topics": [
      "Stack",
      "Design"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": []
  },
  {
    "id": "minimum_height_trees",
    "title": "Minimum Height Trees",
    "difficulty": "Medium",
    "topics": [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "n = 4, edges = [[1,0],[1,2],[1,3]]",
        "output": "[1]"
      },
      {
        "input": "n = 6, edges = [[3,0],[3,1],[3,2],[3,4],[5,4]]",
        "output": "[3,4]"
      }
    ]
  },
  {
    "id": "minimum_window_substring",
    "title": "Minimum Window Substring",
    "difficulty": "Hard",
    "topics": [
      "Hash Table",
      "String",
      "Sliding Window"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "s = \"ADOBECODEBANC\", t = \"ABC\"",
        "output": "\"BANC\""
      },
      {
        "input": "s = \"a\", t = \"a\"",
        "output": "\"a\""
      }
    ]
  },
  {
    "id": "missing_number",
    "title": "Missing Number",
    "difficulty": "Easy",
    "topics": [
      "Array",
      "Hash Table",
      "Math",
      "Binary Search",
      "Bit Manipulation",
      "Sorting"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "nums = [3,0,1]",
        "output": "2"
      },
      {
        "input": "nums = [0,1]",
        "output": "2"
      }
    ]
  },
  {
    "id": "next_permutation",
    "title": "Next Permutation",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Two Pointers"
    ],
    "tags": [
      "grind"
    ],
    "examples": [
      {
        "input": "nums = [1,2,3]",
        "output": "[1,3,2]"
      },
      {
        "input": "nums = [3,2,1]",
        "output": "[1,2,3]"
      }
    ]
  },
  {
    "id": "non_overlapping_intervals",
    "title": "Non-overlapping Intervals",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Dynamic Programming",
      "Greedy",
      "Sorting"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "blind-75"
    ],
    "examples": [
      {
        "input": "intervals = [[1,2],[2,3],[3,4],[1,3]]",
        "output": "1"
      },
      {
        "input": "intervals = [[1,2],[1,2],[1,2]]",
        "output": "2"
      }
    ]
  },
  {
    "id": "number_of_1_bits",
    "title": "Number of 1 Bits",
    "difficulty": "Easy",
    "topics": [
      "Divide and Conquer",
      "Bit Manipulation"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "n = 11",
        "output": "3"
      },
      {
        "input": "n = 128",
        "output": "1"
      }
    ]
  },
  {
    "id": "number_of_connected_components_in_an_undirected_graph",
    "title": "Number of Connected Components in an Undirected Graph",
    "difficulty": "Medium",
    "topics": [
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Graph"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "n = 5 and edges = [[0, 1], [1, 2], [3, 4]]",
        "output": "2"
      },
      {
        "input": "n = 5 and edges = [[0, 1], [1, 2], [2, 3], [3, 4]]",
        "output": "1"
      }
    ]
  },
  {
    "id": "number_of_islands",
    "title": "Number of Islands",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Matrix"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "grid = [",
        "output": "1"
      },
      {
        "input": "grid = [",
        "output": "3"
      }
    ]
  },
  {
    "id": "odd_even_linked_list",
    "title": "Odd Even Linked List",
    "difficulty": "Medium",
    "topics": [
      "Linked List"
    ],
    "tags": [
      "grind"
    ],
    "examples": [
      {
        "input": "head = [1,2,3,4,5]",
        "output": "[1,3,5,2,4]"
      },
      {
        "input": "head = [2,1,3,5,6,4,7]",
        "output": "[2,3,6,7,1,5,4]"
      }
    ]
  },
  {
    "id": "pacific_atlantic_water_flow",
    "title": "Pacific Atlantic Water Flow",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Matrix"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75"
    ],
    "examples": [
      {
        "input": "heights = [[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]",
        "output": "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]"
      },
      {
        "input": "heights = [[1]]",
        "output": "[[0,0]]"
      }
    ]
  },
  {
    "id": "palindrome_partitioning",
    "title": "Palindrome Partitioning",
    "difficulty": "Medium",
    "topics": [
      "String",
      "Dynamic Programming",
      "Backtracking"
    ],
    "tags": [
      "neetcode-150"
    ],
    "examples": [
      {
        "input": "s = \"aab\"",
        "output": "[[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]"
      },
      {
        "input": "s = \"a\"",
        "output": "[[\"a\"]]"
      }
    ]
  },
  {
    "id": "palindromic_substrings",
    "title": "Palindromic Substrings",
    "difficulty": "Medium",
    "topics": [
      "Two Pointers",
      "String",
      "Dynamic Programming"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "s = \"abc\"",
        "output": "3"
      },
      {
        "input": "s = \"aaa\"",
        "output": "6"
      }
    ]
  },
  {
    "id": "partition_equal_subset_sum",
    "title": "Partition Equal Subset Sum",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Dynamic Programming"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "nums = [1,5,11,5]",
        "output": "true"
      },
      {
        "input": "nums = [1,2,3,5]",
        "output": "false"
      }
    ]
  },
  {
    "id": "path_sum_ii",
    "title": "Path Sum II",
    "difficulty": "Medium",
    "topics": [
      "Backtracking",
      "Tree",
      "Depth-First Search",
      "Binary Tree"
    ],
    "tags": [
      "grind"
    ],
    "examples": [
      {
        "input": "root = [5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum = 22",
        "output": "[[5,4,11,2],[5,8,4,5]]"
      },
      {
        "input": "root = [1,2,3], targetSum = 5",
        "output": "[]"
      }
    ]
  },
  {
    "id": "permutations",
    "title": "Permutations",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Backtracking"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "nums = [1,2,3]",
        "output": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"
      },
      {
        "input": "nums = [0,1]",
        "output": "[[0,1],[1,0]]"
      }
    ]
  },
  {
    "id": "product_of_array_except_self",
    "title": "Product of Array Except Self",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Prefix Sum"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "nums = [1,2,3,4]",
        "output": "[24,12,8,6]"
      },
      {
        "input": "nums = [-1,1,0,-3,3]",
        "output": "[0,0,9,0,0]"
      }
    ]
  },
  {
    "id": "ransom_note",
    "title": "Ransom Note",
    "difficulty": "Easy",
    "topics": [
      "Hash Table",
      "String",
      "Counting"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "ransomNote = \"a\", magazine = \"b\"",
        "output": "false"
      },
      {
        "input": "ransomNote = \"aa\", magazine = \"ab\"",
        "output": "false"
      }
    ]
  },
  {
    "id": "remove_nth_node_from_end_of_list",
    "title": "Remove Nth Node From End of List",
    "difficulty": "Medium",
    "topics": [
      "Linked List",
      "Two Pointers"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "blind-75"
    ],
    "examples": [
      {
        "input": "head = [1,2,3,4,5], n = 2",
        "output": "[1,2,3,5]"
      },
      {
        "input": "head = [1], n = 1",
        "output": "[]"
      }
    ]
  },
  {
    "id": "reorder_list",
    "title": "Reorder List",
    "difficulty": "Medium",
    "topics": [
      "Linked List",
      "Two Pointers",
      "Stack",
      "Recursion"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "head = [1,2,3,4]",
        "output": "[1,4,2,3]"
      },
      {
        "input": "head = [1,2,3,4,5]",
        "output": "[1,5,2,4,3]"
      }
    ]
  },
  {
    "id": "reverse_bits",
    "title": "Reverse Bits",
    "difficulty": "Easy",
    "topics": [
      "Divide and Conquer",
      "Bit Manipulation"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "n = 43261596",
        "output": "964176192"
      },
      {
        "input": "n = 2147483644",
        "output": "1073741822"
      }
    ]
  },
  {
    "id": "reverse_integer",
    "title": "Reverse Integer",
    "difficulty": "Medium",
    "topics": [
      "Math"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "x = 123",
        "output": "321"
      },
      {
        "input": "x = -123",
        "output": "-321"
      }
    ]
  },
  {
    "id": "reverse_linked_list",
    "title": "Reverse Linked List",
    "difficulty": "Easy",
    "topics": [
      "Linked List",
      "Recursion"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "head = [1,2,3,4,5]",
        "output": "[5,4,3,2,1]"
      },
      {
        "input": "head = [1,2]",
        "output": "[2,1]"
      }
    ]
  },
  {
    "id": "reverse_linked_list_ii",
    "title": "Reverse Linked List II",
    "difficulty": "Medium",
    "topics": [
      "Linked List"
    ],
    "tags": [
      "**LeetCode:**",
      "[Problem",
      "92](https://leetcode.com/problems/reverse-linked-list-ii/description/)"
    ],
    "examples": [
      {
        "input": "head = [1,2,3,4,5], left = 2, right = 4",
        "output": "[1,4,3,2,5]"
      },
      {
        "input": "head = [5], left = 1, right = 1",
        "output": "[5]"
      }
    ]
  },
  {
    "id": "reverse_nodes_in_k_group",
    "title": "Reverse Nodes in k-Group",
    "difficulty": "Hard",
    "topics": [
      "Linked List",
      "Recursion"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "head = [1,2,3,4,5], k = 2",
        "output": "[2,1,4,3,5]"
      },
      {
        "input": "head = [1,2,3,4,5], k = 3",
        "output": "[3,2,1,4,5]"
      }
    ]
  },
  {
    "id": "rotate_array",
    "title": "Rotate Array",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Math",
      "Two Pointers"
    ],
    "tags": [
      "grind"
    ],
    "examples": [
      {
        "input": "nums = [1,2,3,4,5,6,7], k = 3",
        "output": "[5,6,7,1,2,3,4]"
      },
      {
        "input": "nums = [-1,-100,3,99], k = 2",
        "output": "[3,99,-1,-100]"
      }
    ]
  },
  {
    "id": "rotate_image",
    "title": "Rotate Image",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Math",
      "Matrix"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "blind-75"
    ],
    "examples": [
      {
        "input": "matrix = [[1,2,3],[4,5,6],[7,8,9]]",
        "output": "[[7,4,1],[8,5,2],[9,6,3]]"
      },
      {
        "input": "matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]",
        "output": "[[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]"
      }
    ]
  },
  {
    "id": "rotting_oranges",
    "title": "Rotting Oranges",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Breadth-First Search",
      "Matrix"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "grid = [[2,1,1],[1,1,0],[0,1,1]]",
        "output": "4"
      },
      {
        "input": "grid = [[2,1,1],[0,1,1],[1,0,1]]",
        "output": "-1"
      }
    ]
  },
  {
    "id": "same_tree",
    "title": "Same Tree",
    "difficulty": "Easy",
    "topics": [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "p = [1,2,3], q = [1,2,3]",
        "output": "true"
      },
      {
        "input": "p = [1,2], q = [1,null,2]",
        "output": "false"
      }
    ]
  },
  {
    "id": "search_in_rotated_sorted_array",
    "title": "Search in Rotated Sorted Array",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Binary Search"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "nums = [4,5,6,7,0,1,2], target = 0",
        "output": "4"
      },
      {
        "input": "nums = [4,5,6,7,0,1,2], target = 3",
        "output": "-1"
      }
    ]
  },
  {
    "id": "serialize_and_deserialize_binary_tree",
    "title": "Serialize and Deserialize Binary Tree",
    "difficulty": "Hard",
    "topics": [
      "String",
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Design",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "root = [1,2,3,null,null,4,5]",
        "output": "[1,2,3,null,null,4,5]"
      },
      {
        "input": "root = []",
        "output": "[]"
      }
    ]
  },
  {
    "id": "set_matrix_zeroes",
    "title": "Set Matrix Zeroes",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Hash Table",
      "Matrix"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "matrix = [[1,1,1],[1,0,1],[1,1,1]]",
        "output": "[[1,0,1],[0,0,0],[1,0,1]]"
      },
      {
        "input": "matrix = [[0,1,2,0],[3,4,5,2],[1,3,1,5]]",
        "output": "[[0,0,0,0],[0,4,5,0],[0,3,1,0]]"
      }
    ]
  },
  {
    "id": "sort_colors",
    "title": "Sort Colors",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Two Pointers",
      "Sorting"
    ],
    "tags": [
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "nums = [2,0,2,1,1,0]",
        "output": "[0,0,1,1,2,2]"
      },
      {
        "input": "nums = [2,0,1]",
        "output": "[0,1,2]"
      }
    ]
  },
  {
    "id": "spiral_matrix",
    "title": "Spiral Matrix",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Matrix",
      "Simulation"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "matrix = [[1,2,3],[4,5,6],[7,8,9]]",
        "output": "[1,2,3,6,9,8,7,4,5]"
      },
      {
        "input": "matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]",
        "output": "[1,2,3,4,8,12,11,10,9,5,6,7]"
      }
    ]
  },
  {
    "id": "string_to_integer_atoi",
    "title": "String to Integer (atoi)",
    "difficulty": "Medium",
    "topics": [
      "String"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "s = \"42\"",
        "output": "42"
      },
      {
        "input": "s = \"   -042\"",
        "output": "-42"
      }
    ]
  },
  {
    "id": "subsets",
    "title": "Subsets",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Backtracking",
      "Bit Manipulation"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "nums = [1,2,3]",
        "output": "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]"
      },
      {
        "input": "nums = [0]",
        "output": "[[],[0]]"
      }
    ]
  },
  {
    "id": "subtree_of_another_tree",
    "title": "Subtree of Another Tree",
    "difficulty": "Easy",
    "topics": [
      "Tree",
      "Depth-First Search",
      "String Matching",
      "Binary Tree",
      "Hash Function"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "root = [3,4,5,1,2], subRoot = [4,1,2]",
        "output": "true"
      },
      {
        "input": "root = [3,4,5,1,2,null,null,null,null,0], subRoot = [4,1,2]",
        "output": "false"
      }
    ]
  },
  {
    "id": "sum_of_two_integers",
    "title": "Sum of Two Integers",
    "difficulty": "Medium",
    "topics": [
      "Math",
      "Bit Manipulation"
    ],
    "tags": [
      "neetcode-150",
      "blind-75"
    ],
    "examples": [
      {
        "input": "a = 1, b = 2",
        "output": "3"
      },
      {
        "input": "a = 2, b = 3",
        "output": "5"
      }
    ]
  },
  {
    "id": "swap_nodes_in_pairs",
    "title": "Swap Nodes in Pairs",
    "difficulty": "Medium",
    "topics": [
      "Linked List",
      "Recursion"
    ],
    "tags": [
      "algo-master-75",
      "grind"
    ],
    "examples": [
      {
        "input": "head = [1,2,3,4]",
        "output": "[2,1,4,3]"
      },
      {
        "input": "head = []",
        "output": "[]"
      }
    ]
  },
  {
    "id": "task_scheduler",
    "title": "Task Scheduler",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Hash Table",
      "Greedy",
      "Sorting",
      "Heap (Priority Queue)",
      "Counting"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "tasks = [\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"], n = 2",
        "output": "8"
      },
      {
        "input": "tasks = [\"A\",\"C\",\"A\",\"B\",\"D\",\"B\"], n = 1",
        "output": "6"
      }
    ]
  },
  {
    "id": "three_sum",
    "title": "3Sum",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Two Pointers",
      "Sorting"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "nums = [-1,0,1,2,-1,-4]",
        "output": "[[-1,-1,2],[-1,0,1]]"
      },
      {
        "input": "nums = [0,1,1]",
        "output": "[]"
      }
    ]
  },
  {
    "id": "time_based_key_value_store",
    "title": "Time Based Key-Value Store",
    "difficulty": "Medium",
    "topics": [
      "Hash Table",
      "String",
      "Binary Search",
      "Design"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "grind-75"
    ],
    "examples": []
  },
  {
    "id": "top_k_frequent_elements",
    "title": "Top K Frequent Elements",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Hash Table",
      "Divide and Conquer",
      "Sorting",
      "Heap (Priority Queue)",
      "Bucket Sort",
      "Counting",
      "Quickselect"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "blind-75"
    ],
    "examples": [
      {
        "input": "nums = [1,1,1,2,2,3], k = 2",
        "output": "[1,2]"
      },
      {
        "input": "nums = [1], k = 1",
        "output": "[1]"
      }
    ]
  },
  {
    "id": "top_k_frequent_words",
    "title": "Top K Frequent Words",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Hash Table",
      "String",
      "Trie",
      "Sorting",
      "Heap (Priority Queue)",
      "Bucket Sort",
      "Counting"
    ],
    "tags": [
      "grind"
    ],
    "examples": [
      {
        "input": "words = [\"i\",\"love\",\"leetcode\",\"i\",\"love\",\"coding\"], k = 2",
        "output": "[\"i\",\"love\"]"
      },
      {
        "input": "words = [\"the\",\"day\",\"is\",\"sunny\",\"the\",\"the\",\"the\",\"sunny\",\"is\",\"is\"], k = 4",
        "output": "[\"the\",\"is\",\"sunny\",\"day\"]"
      }
    ]
  },
  {
    "id": "trapping_rain_water",
    "title": "Trapping Rain Water",
    "difficulty": "Hard",
    "topics": [
      "Array",
      "Two Pointers",
      "Dynamic Programming",
      "Stack",
      "Monotonic Stack"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "height = [0,1,0,2,1,0,1,3,2,1,2,1]",
        "output": "6"
      },
      {
        "input": "height = [4,2,0,3,2,5]",
        "output": "9"
      }
    ]
  },
  {
    "id": "two_sum",
    "title": "Two Sum",
    "difficulty": "Easy",
    "topics": [
      "Array",
      "Hash Table"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "nums = [2,7,11,15], target = 9",
        "output": "[0,1]"
      },
      {
        "input": "nums = [3,2,4], target = 6",
        "output": "[1,2]"
      }
    ]
  },
  {
    "id": "unique_paths",
    "title": "Unique Paths",
    "difficulty": "Medium",
    "topics": [
      "Math",
      "Dynamic Programming",
      "Combinatorics"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "m = 3, n = 7",
        "output": "28"
      },
      {
        "input": "m = 3, n = 2",
        "output": "3"
      }
    ]
  },
  {
    "id": "valid_anagram",
    "title": "Valid Anagram",
    "difficulty": "Easy",
    "topics": [
      "Hash Table",
      "String",
      "Sorting"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "s = \"anagram\", t = \"nagaram\"",
        "output": "true"
      },
      {
        "input": "s = \"rat\", t = \"car\"",
        "output": "false"
      }
    ]
  },
  {
    "id": "valid_palindrome",
    "title": "Valid Palindrome",
    "difficulty": "Easy",
    "topics": [
      "Two Pointers",
      "String"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "s = \"A man, a plan, a canal: Panama\"",
        "output": "true"
      },
      {
        "input": "s = \"race a car\"",
        "output": "false"
      }
    ]
  },
  {
    "id": "valid_parentheses",
    "title": "Valid Parentheses",
    "difficulty": "Easy",
    "topics": [
      "String",
      "Stack"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "s = \"()\"",
        "output": "true"
      },
      {
        "input": "s = \"()[]{}\"",
        "output": "true"
      }
    ]
  },
  {
    "id": "valid_sudoku",
    "title": "Valid Sudoku",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Hash Table",
      "Matrix"
    ],
    "tags": [
      "neetcode-150",
      "grind"
    ],
    "examples": [
      {
        "input": "board =",
        "output": "true"
      },
      {
        "input": "board =",
        "output": "false"
      }
    ]
  },
  {
    "id": "validate_binary_search_tree",
    "title": "Validate Binary Search Tree",
    "difficulty": "Medium",
    "topics": [
      "Tree",
      "Depth-First Search",
      "Binary Search Tree",
      "Binary Tree"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "root = [2,1,3]",
        "output": "true"
      },
      {
        "input": "root = [5,1,4,null,null,3,6]",
        "output": "false"
      }
    ]
  },
  {
    "id": "word_break",
    "title": "Word Break",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Hash Table",
      "String",
      "Dynamic Programming",
      "Trie",
      "Memoization"
    ],
    "tags": [
      "neetcode-150",
      "grind",
      "blind-75",
      "grind-75",
      "algo-master-75"
    ],
    "examples": [
      {
        "input": "s = \"leetcode\", wordDict = [\"leet\",\"code\"]",
        "output": "true"
      },
      {
        "input": "s = \"applepenapple\", wordDict = [\"apple\",\"pen\"]",
        "output": "true"
      }
    ]
  },
  {
    "id": "word_ladder",
    "title": "Word Ladder",
    "difficulty": "Hard",
    "topics": [
      "Hash Table",
      "String",
      "Breadth-First Search"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "beginWord = \"hit\", endWord = \"cog\", wordList = [\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]",
        "output": "5"
      },
      {
        "input": "beginWord = \"hit\", endWord = \"cog\", wordList = [\"hot\",\"dot\",\"dog\",\"lot\",\"log\"]",
        "output": "0"
      }
    ]
  },
  {
    "id": "word_search",
    "title": "Word Search",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "String",
      "Backtracking",
      "Depth-First Search",
      "Matrix"
    ],
    "tags": [
      "neetcode-150",
      "blind-75",
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCCED\"",
        "output": "true"
      },
      {
        "input": "board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"SEE\"",
        "output": "true"
      }
    ]
  },
  {
    "id": "word_search_ii",
    "title": "Word Search II",
    "difficulty": "Hard",
    "topics": [
      "Array",
      "String",
      "Backtracking",
      "Trie",
      "Matrix"
    ],
    "tags": [
      "neetcode-150",
      "algo-master-75",
      "blind-75"
    ],
    "examples": [
      {
        "input": "board = [[\"o\",\"a\",\"a\",\"n\"],[\"e\",\"t\",\"a\",\"e\"],[\"i\",\"h\",\"k\",\"r\"],[\"i\",\"f\",\"l\",\"v\"]], words = [\"oath\",\"pea\",\"eat\",\"rain\"]",
        "output": "[\"eat\",\"oath\"]"
      },
      {
        "input": "board = [[\"a\",\"b\"],[\"c\",\"d\"]], words = [\"abcb\"]",
        "output": "[]"
      }
    ]
  },
  {
    "id": "zero_one_matrix",
    "title": "01 Matrix",
    "difficulty": "Medium",
    "topics": [
      "Array",
      "Dynamic Programming",
      "Breadth-First Search",
      "Matrix"
    ],
    "tags": [
      "grind",
      "grind-75"
    ],
    "examples": [
      {
        "input": "mat = [[0,0,0],[0,1,0],[0,0,0]]",
        "output": "[[0,0,0],[0,1,0],[0,0,0]]"
      },
      {
        "input": "mat = [[0,0,0],[0,1,0],[1,1,1]]",
        "output": "[[0,0,0],[0,1,0],[1,2,1]]"
      }
    ]
  }
] as Problem[];
